### ISSUE TITLE
Car ownership

### ISSUE THREAD

**Issue by weespin** [lightphoenix2/LPX#10]
Why i should re-buy my car after some time.
When i buy a car i'm registering a license code for example 13
And when i spawned another car i can buy car with same code 13.
I cant have 2 cars at same time?
And why after some time my onwnership is dropping?
I want to make my car locked forever. :)
Maximum cars on maps = 25?

**Comment by lightphoenix2** [comment]
Is your car destroyed? If it is, you will lose the ownership.
Im not sure what is the maximum allowable cars on the map.

**Comment by weespin** [comment]
Car isnt destroyed i mean a lot of cars are having same license id for me.
