### ISSUE TITLE
Permissions and Configuration

### ISSUE THREAD

**Issue by JustOneMoreBlock** [lightphoenix2/LPX#11]
Hello,

This is my current config for LIGHT.
http://pastebin.com/raw/fqDMa5WS (MySQL information has been REDACTED.)

I'm usually all for using MySQL with permissions. However, I've adapted to a system that connects to my forum database to give permissions to users. This will eventually include donation ranks.

I'm interested in NOT using the permissions part of this plugin. Therefore, I've disabled:
<LPXEnabled>false</LPXEnabled>
Am I to assume this will disable the permissions system? As of right now, Light is installed and it's using my web permissions.

However, Kits is enabled and added all the permissions using the web based system and says I don't have access to that command. Although, I have '*' permissions in the web database. I've even added it manually and got the same response.

Permissions File:
https://justplayhere.com/utperms.php

With that said, I was able to use the car commands with a problem using the '*' permissions using the web system.

Add a configuration option to make vehicle licenses not required in order to drive a non-owned/non-licensed vehicle. So that the license is optional if the player wants their vehicle protected from theft.
- Cory

**Comment by lightphoenix2** [comment]
Hi Cory,

You are require to add the permission "kit" and "kit._" together to use the command. The permission "kit" allow you to use the /kit command. The kit._ grants you permission to all the kits, but does not grant the command /kit. Also, I have not remove the dependency on mySQLPermission for the kits . I will change this in the next few updates. And you said that you are using the car command with a problem? 

If I'm not wrong, someone did mention something like that in the comments, maybe its you =3

I will also update it in a weeks time. This week I am having my final exam.

**Comment by JustOneMoreBlock** [comment]
```
    <Group>
      <Id>owner</Id>
      <DisplayName>Owner</DisplayName>
      <Color>aa0000</Color>
      <Members><Member>76561198066176197</Member>
      </Members>
      <Commands>
        <Command>essentials.*</Command>
        <Command>kit</Command>
        <Command>kit.*</Command>
        <Command>kits</Command>
        <Command>kits.*</Command>
        <Command>*</Command>
      </Commands>
      <ParentGroup>admin</ParentGroup>
    </Group>
```

Added them manually and it's the same result. However, inheritance should have taken place and another kit wouldn't be required as I already gave it to the default group.

The car command works fine, yes and I have '*' permissions setup for that. Never added any permissions as I'm in the testing phase with your plugin and uEssentials which also has conflicts. I've reported over there.

**Comment by lightphoenix2** [comment]
As I have mentioned,  I have not remove the dependency on mySQLPermission for the kits. So it requires LPX enabled for it to work. I have already change the code and will release it soon.
