### ISSUE TITLE
Problem of Kit

### ISSUE THREAD

**Issue by tester00125** [lightphoenix2/LPX#13]
I have a trouble with kit function. I have a kit name free in DB and players can use "/kit free" in sometime and they get error "you do not have permission" in sometime.

this is LPX config fiel : http://pastebin.com/iF3hqSFn
this is command config file : http://pastebin.com/nyGn2ZV5

FYI : Now if I delete players data in server/player folder and clean up lpx table in DB user can use "/kit free" 1 time after that get error "do noy have permisssion"

**Comment by lightphoenix2** [comment]
Did you give them the permission "kit"?

Date: Fri, 11 Mar 2016 03:04:44 -0800

**Comment by tester00125** [comment]
Yes, I already add  permission "kit"  to group.

I have kit plugin on my server too. Is it cause of trouble ?

**Comment by lightphoenix2** [comment]
It may conflict if this plugin, if you have a kit plugin.

**Comment by ndv400** [comment]
@lightphoenix2 uncheck "Enable Avast Email Signature" in your Avast settings, pls. Just a friendly advice...

**Comment by tester00125** [comment]
Now, everything working. I don't know why but thank you lightphoenix2
