### ISSUE TITLE
removepermission command

### ISSUE THREAD

**Issue by jorea143** [lightphoenix2/LPX#2]
Hi light,

I am not sure if you read my comment on rocket when I said that the command "/lpx removepermisson" is not working as intended. Instead of removing a specified command, it actually re-adds it. Hence two or more entries of said command can be found on mysql database. I have not extensively test all other commands, so I can't say if other commands are working as designed.

Please have this fix whenever you have time.

Thank you.

**Comment by lightphoenix2** [comment]
I have tested it on my server. It remove the permission correctly. Maybe I didn't upload the latest version. =3
