### ISSUE TITLE
Kits problem.

### ISSUE THREAD

**Issue by weespin** [lightphoenix2/LPX#20]
Hello, Lightphoenix.
Kits config isnt working.
Config:
`<KitsEnabled>true</KitsEnabled>
`
In rocket commands config
`
    <Command Name="kits" Enabled="false" Priority="Normal">LIGHT.CommandKits/kits</Command>
    <Command Name="kit" Enabled="false" Priority="Normal">LIGHT.CommandKit/kit</Command>
    <Command Name="kits" Enabled="true" Priority="Normal">fr34kyn01535.Kits.CommandKits/kits</Command>
    <Command Name="kit" Enabled="true" Priority="Normal">fr34kyn01535.Kits.CommandKit/kit</Command>`
But i dont have Kits plugin installed. ._. 
plz help

**Comment by lightphoenix2** [comment]
Oh, this have something to do with Kits Plugin. You must have installed it previously right?

**Comment by weespin** [comment]
Yep, but i deleted Kit plugin. And removed Rocket Commands file, restarted rocket. But i have this buug. but when i type /kits, server is responding command_not_found
:3

**Comment by Riddler76** [comment]
```
<Command Name="kits" Enabled="true" Priority="Normal">LIGHT.CommandKits/kits</Command>
```

**Comment by lightphoenix2** [comment]
This have something to do with the Rocket command loading, it saves a file for all the previously loaded commands. It must still be enabled. Trying removing that file Commands.config.xml
