### ISSUE TITLE
Don't create the initial table in the DDB

### ISSUE THREAD

**Issue by Minege** [lightphoenix2/LPX#25]
The LIGHT plugin don't create the initial table for lpx permissions, but works for car, items, shop, etc.

When i try to create something, or when a player join, the console say errors and i can see : Can't find unturned_data.lpx

I don't know the initial schema of lpx, so i can't create it, and the plugin don't create it.

**Comment by Riddler76** [comment]
I upload you structure.

http://screenshots.freeforfriends.fr/repository/RidShots/unturned%284%29.sql

**Comment by Minege** [comment]
Thanks !
