### ISSUE TITLE
Update QUICKLY PLEASE

### ISSUE THREAD

**Issue by Minege** [lightphoenix2/LPX#29]
Please, update the plugin for the last version of Rocket quickly, because i use it for my main server and people and crying about that !

**Comment by Minege** [comment]
PS: I use the last version of unturned, and the last version of rocketmod.

**Comment by Riddler76** [comment]
Hey, for me the actual version is Ok, what is your problem ?

**Comment by Minege** [comment]
Hey ! I've fixed, just an internal problem ! Thank you !
