### ISSUE TITLE
automatically add default users to db

### ISSUE THREAD

**Issue by odyss3y** [lightphoenix2/LPX#3]
I'm running 4.8.0.0 and users aren't being automatically added to the DB, this means their hours aren't being tracked and they aren't getting promoted.

**Comment by lightphoenix2** [comment]
Well, Normal users won't be tracked. I want to be able to track a selected few people. Its easier to manage your staff and your players. There will be some who would join and never come back. This cause the DB to be over crowded, also takes longer time to load. You either have to add them yourself or your staff to add them in.

**Comment by odyss3y** [comment]
well you track lastlogin, why not just prune with a "hasnt logged in since xx days" option? i was hoping to promote people who have been loyal to the server but maybe havent interacted with an admin. they get a bump in pay, extra kits, etc. or track them only after theyve been on for an hour. i think there would be a lot of ways to make this work and would appreciate if you added the feature.

**Comment by odyss3y** [comment]
i see the new version, thanks! i'll let you know how it goes.
