### ISSUE TITLE
Kits Cooldown problem

### ISSUE THREAD

**Issue by Nalik68** [lightphoenix2/LPX#33]
Hello ! 

I just started with unturned servers, everything is working fine expect the LPX kits. Let me explain when i do the basic kit survival that was already installed with the plugin the cooldown works but with my custom kits that i created on the DB that's weird, the kit works i get the item but it doesnt tell "You have received the kit XXX" and there is no cooldown neither i can spam them. And i don't know why this is happening since i did exactly like the survival kit I can send screen of the DB if needed.
Hope u will help me.

the console is telling me that : 
https://gyazo.com/6009f1b37b70e0e5d00487d6074d84de

**Comment by lightphoenix2** [comment]
I am not experience that issue you are facing. I need more information to help you.

**Comment by Nalik68** [comment]
no problem, I decided to create some more kits screen : https://gyazo.com/dd90695f0f95e825f7345b6e69d6d6b6.png

you can see that I put the cooldown, i did the permissions in the DB : 
https://gyazo.com/9fc6f67c952e0ebebfeadac711079f86.png

but when i write /kit sniper for exemple it give me the kit but it doesnt tell "you receive the kit sniper" and the cooldown isnt applied neither I can spam the kit.
I checked the console and got those error lines.
Checked other issues and looks like im not the only one getting this error.

Oh i changed updategroup and updatetime I don't know if it affect my problem I don't know the utility of these fields :s

**Comment by lightphoenix2** [comment]
Okay Noted, I will find the problem.

**Comment by Nalik68** [comment]
Thanks you !

**Comment by lightphoenix2** [comment]
Strangely, I am unable to replicate the result you are facing. Maybe I can suggest you delete Commands.config.xml under "Rocket" folder.

**Comment by Nalik68** [comment]
I checked the other issues and saw u already told that to another one then i tried it but it didnt solve the problem i'll try to reinstall the plugin maybe it will work atleast i hope

**Comment by Nalik68** [comment]
well reinstalled everything but still the problem don't know maybe an futur update will solve it xd

https://gyazo.com/157eaa3dab123853cd6cd09b89451143

**Comment by lightphoenix2** [comment]
May I have more information, like your Group, are you a admin etc..

**Comment by Nalik68** [comment]
Yup i'm admin but i tried on a alt account where i was in a group i created to get X kit 
https://gyazo.com/e54bec8097e919443322dd04eaccd187

but I decided tp use uessential kits it works now but i prefered ur DB kits its easier to create kits and i know i'm taking lot of your time but if you could tell met what are the uses of updategroup and time i'm lost

**Comment by lightphoenix2** [comment]
Updategroup is the name of the group that it is changing to. For example, if you are in group default, and your Updategroup is VIP, when the user spent time in the server for the amount of time you state in UpdateTime, let say 5. In 5 hours, he will change from group default to group VIP. Ultimately, you must make UpdateEnable true or it will be disabled.

**Comment by Nalik68** [comment]
Thanks you for your amazing support !
